### ISSUE TITLE
index.d.ts

### ISSUE THREAD

**Issue by temp3l** [flipbyte/formik-json-schema#25]
Could you provide index.d.ts ?

**Comment by easeq** [comment]
I haven't used typescript in this project. Any specific reason you can't work with index.js?

**Comment by gunzip** [comment]
I second this one. If you have aTypescript project you must write your own typings for the React elements, otherwise you cannot neither import them:

![image](https://user-images.githubusercontent.com/148224/57866229-4c2e9d80-77ff-11e9-9c2f-68440cb8e4f6.png)

This is a showstopper for us.

I think that converting the project to Typescript as a whole would add a significant value.

**Comment by uragecz** [comment]
Any specific reason? 😂  Typescript is these days standard.. So +- this library is unusable... Otherwise it would take so much time to find all those types that i need to type

**Comment by easeq** [comment]
There were plans on converting the whole project to Typescript, but due to time constraints I haven’t been able to do so yet. Create a PR if you can and I would be happy to merge if everything is in order.
