### ISSUE TITLE
Position prop in elements not used?

### ISSUE THREAD

**Issue by compojoom** [flipbyte/formik-json-schema#39]
### Describe the bug
The elements definition in the schema is an Object. The js engine however is not required to output the props in the order they are defined in the source code. Chrome seems to be outputing the elements in the defined order, but on iOS my elements end up in the wrong order. 

In the repository readme we have a position prop and I assumed that it's used to define the order of the elements. I did a fast search through the code base and I  couldn't find where it's used?

I use the form container for now, so adding a `_.map(_.orderBy(elements, 'position')` ... seems to fix my issue. Shall I create a pull request or is there something I'm missing?

**Comment by easeq** [comment]
The idea was to handle element positioning within formik-json, but then we dropped the idea because it seems unnecessary to handle positioning within formik-json as the schema object is not usually overridden to have the elements out of order. 

The schema object should already be prepared to have all the elements in order before passing it to formik-json to avoid unnecessary processing of field order.

I must have missed to update the README.
